const games = [
  {
    title: "Terraforming Mars",
    category: "Board",
    price: 68.99,
    desc: "Catan like boardgame where you and your company are in charge of making Mars livable.",
    qty: 5,
    img: "https://example.com/images/terraforming-mars.jpg",
  },
  {
    title: "Codenames",
    category: "Card",
    price: 19.95,
    desc: "A party word game where teams compete to uncover all their agents first.",
    qty: 12,
    img: "https://example.com/images/codenames.jpg",
  },
  {
    title: "Elden Ring",
    category: "Video",
    price: 59.99,
    desc: "An open-world fantasy RPG with challenging combat and a deep lore-rich world.",
    qty: 7,
    img: "https://example.com/images/elden-ring.jpg",
  },
  {
    title: "Spikeball",
    category: "Outdoor",
    price: 34.99,
    desc: "A fast-paced 2v2 outdoor ball game similar to volleyball but played around a trampoline.",
    qty: 9,
    img: "https://example.com/images/spikeball.jpg",
  },
  {
    title: "Yahtzee",
    category: "Dice",
    price: 12.99,
    desc: "Classic dice game where you roll combinations to score the most points.",
    qty: 15,
    img: "https://example.com/images/yahtzee.jpg",
  },
  {
    title: "Exploding Kittens",
    category: "Card",
    price: 24.99,
    desc: "A highly-strategic, kitty-powered version of Russian roulette.",
    qty: 10,
    img: "https://example.com/images/exploding-kittens.jpg",
  },
  {
    title: "Monopoly",
    category: "Board",
    price: 29.99,
    desc: "Buy, sell, and scheme your way to riches in this classic real estate board game.",
    qty: 20,
    img: "https://example.com/images/monopoly.jpg",
  },
  {
    title: "VR Ping Pong Pro",
    category: "Video",
    price: 14.99,
    desc: "A realistic VR ping pong simulation game with multiple difficulty levels.",
    qty: 4,
    img: "https://example.com/images/vr-ping-pong.jpg",
  },
  {
    title: "KanJam",
    category: "Outdoor",
    price: 39.95,
    desc: "A flying disc game where teams try to land a disc in a slotted can.",
    qty: 6,
    img: "https://example.com/images/kanjam.jpg",
  },
  {
    title: "Custom Dice Set",
    category: "Other",
    price: 9.99,
    desc: "A set of artisan dice for tabletop RPGs and custom board games.",
    qty: 25,
    img: "https://example.com/images/custom-dice.jpg",
  },
];

export default games;